#!/bin/sh -ex

export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

getent group  postgres || groupadd -r postgres
getent passwd postgres || useradd  -g postgres -r -d /var/pgsql/data \
	-s /bin/false postgres

passwd -l postgres

if [ ! -d /var/pgsql/data ]; then
	install -o postgres -g postgres -d /var/pgsql/data
	su -s /bin/sh -c "pg_ctl -D /var/pgsql/data initdb" postgres
fi

# End of file.
