#
# /etc/wpa_supplicant.conf: configuration for wpa_supplicant(8)
#
# Reload configuration:
#   - killall -HUP wpa_supplicant
#   - wpa_cli reconfigure
#   - /etc/rc.d/wpa_supplicant reload
#
# For full syntax and options, see wpa_supplicant.conf(5).
#

# Location of the control interface socket
ctrl_interface=/run/wpa_supplicant

# End of file.
