.Dd November 17, 2023
.Dt UPDATE-CA-TRUST 1
.Os
.Sh NAME
.Nm update-ca-trust
.Nd update anchors and certificate stores on the system
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a command line tools to both extract local certificates from an
updated anchor store, and regenerate all anchors and certificate
stores on the system.
.Pp
This is done unconditionally on Zeppe-Lin system using the
.Fl f
and
.Fl g
flags to
.Xr make-ca
and should likely not be used for automated updates.
.Sh SEE ALSO
.Xr make-ca 1
