=pod

=encoding UTF-8

=head1 NAME

fsck.ntfs - check and repair NTFS filesystems

=head1 SYNOPSIS

B<fsck.ntfs> [I<OPTIONS>] I<DEVICE>

=head1 DESCRIPTION

B<fsck.ntfs> is a wrapper script around L<ntfsfix(8)> that silently
discards any unsupported flags from F</etc/rc>'s L<fsck(8)>.

=head1 AVAILABILITY

B<fsck.ntfs> is I<NOT> part of upstream B<ntfs-3g> package.

=head1 SEE ALSO

L<ntfsfix(8)>

=cut
