#!/bin/sh -ex
export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

getent group  dhcpcd >/dev/null || groupadd -r dhcpcd
getent passwd dhcpcd >/dev/null || useradd  -g dhcpcd -r \
	-d /var/lib/dhcpcd -s /bin/false dhcpcd

passwd -l dhcpcd
chown -R dhcpcd:dhcpcd /var/lib/dhcpcd

# End of file.
