#!/bin/sh -ex
export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

# Generate initramfs if mkinitramfs is installed.
if pkgman isinst mkinitramfs; then
	_KVER=$(pkgman printf %v --filter=linux)
	mkinitramfs -o /boot/initramfs-$_KVER.img -k $_KVER -f
fi

# Update grub configuration if grub2 is installed.
if pkgman isinst grub2; then
	mkdir -p /boot/grub
	grub-mkconfig -o /boot/grub/grub.cfg
fi

# End of file.
