#!/bin/sh -ex

# prepare initramfs if mkinitramfs is installed
if pkgman isinst mkinitramfs; then
	_KVER=$(pkgman printf %v --filter=linux)
	mkinitramfs -o /boot/initramfs-$_KVER.img -k $_KVER -f
fi

# update grub configuration file if installed
if pkgman isinst grub2; then
	if [ ! -d /boot/grub ]; then
		mkdir -p /boot/grub
	fi
	grub-mkconfig -o /boot/grub/grub.cfg
fi

# End of file.
