#!/bin/sh -ex
export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

# If mkinitramfs and linux are installed, remove the old initramfs.
# A new one will be generated in the post-install step.
if pkgman isinst mkinitramfs linux; then
	_KVER=$(pkgman current linux | cut -d- -f1)
	rm -v /boot/initramfs-"$_KVER".img
fi

# End of file.
